const ACTIVE_RECORD = 10
const PROJECT_STATUS_OK = ACTIVE_RECORD
const BULK_MAX_SIZE = 500
const DEFAULT_CONNECTION_LIMIT = 10
const BULK_PAGE_SIZE = 1000 // "page size"
const UI_PAGE_SIZE = 20
const ACQUIRE_TIME_OUT = 60 * 60 * 1000

module.exports = { ACTIVE_RECORD, PROJECT_STATUS_OK, BULK_MAX_SIZE, DEFAULT_CONNECTION_LIMIT, BULK_PAGE_SIZE, UI_PAGE_SIZE, ACQUIRE_TIME_OUT }
