USE `${DB_MAIN}`;
DROP TABLE IF EXISTS `PeriodGoal`;

CREATE TABLE IF NOT EXISTS `PeriodGoal`
(
    `Period` INT NOT NULL,
    AxisId INT UNSIGNED NOT NULL,
    `Level1` DECIMAL(16,3) NOT NULL,
    `Level2` DECIMAL(16,3) NOT NULL,
    `Level3` DECIMAL(16,3) NOT NULL,
    `Level4` DECIMAL(16,3) NOT NULL,
    `Status` SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT PeriodGoal_pk PRIMARY KEY (`Period`, AxisId)
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE PeriodGoal
ADD CONSTRAINT PeriodGoal_AxisId_fk 
FOREIGN KEY (AxisId) REFERENCES Axis(Id);